### ISSUE TITLE
Terminali açtım, şimdi ne yapmayılım  :l

### ISSUE THREAD

**Issue by semihmasat** [miratcan/FriendFeed-Tools#3]
Benim gibi linux kullanımı konusunda bir nane bilmeyen insanlar için çok minik te olsa bi açıklama yapabilir misiniz acaba?

**Comment by miratcan** [comment]
gnome-terminal'i açıp o klasöre git, klasör içindeyken

```
python migrate.py {feedidin]
```

yazarak işlemi başlatabilirsin. eğer round ceiling hatası çıkar ise aşağıdaki komutu deneyip tekrar deneyin

```
LANG=en_US.UTF8
```

**Comment by semihmasat** [comment]
1800 entries collected dedikten sonra aşağıdaki gibi hatalar aldım.

Starting localization
0 entries localized.
1 entries localized.
2 entries localized.
3 entries localized.
Traceback (most recent call last):
  File "migrate.py", line 69, in <module>
    main()
  File "migrate.py", line 61, in main
    localized_data = localizer.run()
  File "/home/semihmasat/Masaüstü/ff/ffmigration/localizers.py", line 54, in run
    self._localize_thumbnails(entry)
  File "/home/semihmasat/Masaüstü/ff/ffmigration/localizers.py", line 99, in _localize_thumbnails
    self._queue_download(thumbnail['url'], self._filename_for_thumbnail(thumbnail))
  File "/home/semihmasat/Masaüstü/ff/ffmigration/localizers.py", line 118, in _filename_for_thumbnail
    return join(self.thumbnails_path, slugify(urlparse.urlparse(thumbnail['url']).path[1:]))
  File "/usr/lib/python2.7/posixpath.py", line 71, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 21: ordinal not in range(128)

**Comment by miratcan** [comment]
hmmm.. içinde türkçe karakter olmayan bir klasörde çalıştırmayı dener misin? "Masaüstü" işi bozuyor sanırım

**Comment by miratcan** [comment]
tamam heralde kapatıyorum konuyu
